name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        ninja-build

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build          \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}     \
        -DBUILD_TESTS=ON                                \
        -GNinja

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test
